"""cria tabelas usuario e municipio

Revision ID: 3fcc26dbcb62
Revises: 
Create Date: 2025-04-16 16:56:38.869611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fcc26dbcb62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('municipios',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('codigo_ibge', sa.Integer(), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('municipio_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'municipios', ['municipio_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('municipio_id')

    op.drop_table('municipios')
    # ### end Alembic commands ###
