namespace: development
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: mysql
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: ibge_app_dev
